"""empty message

Revision ID: d02ec002f703
Revises: 
Create Date: 2017-03-22 13:45:50.464309

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'd02ec002f703'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('pn', sa.TEXT(), nullable=True),
    sa.Column('scc', sa.TEXT(), nullable=True),
    sa.Column('celula', sa.TEXT(), nullable=True),
    sa.Column('cnc', sa.TEXT(), nullable=True),
    sa.Column('cnc_sw_ver', sa.TEXT(), nullable=True),
    sa.Column('mon_hw_ver', sa.TEXT(), nullable=True),
    sa.Column('mon_sw_ver', sa.TEXT(), nullable=True),
    sa.Column('img_filename', sa.TEXT(), nullable=True),
    sa.Column('manual_filename', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sqlite.DATE(), nullable=True),
    sa.Column('resp_name', sa.TEXT(), nullable=True),
    sa.Column('prod_amount_t1', sa.INTEGER(), nullable=True),
    sa.Column('prod_amount_t2', sa.INTEGER(), nullable=True),
    sa.Column('prod_amount_t3', sa.INTEGER(), nullable=True),
    sa.Column('op_amount_t1', sa.INTEGER(), nullable=True),
    sa.Column('op_amount_t2', sa.INTEGER(), nullable=True),
    sa.Column('op_amount_t3', sa.INTEGER(), nullable=True),
    sa.Column('idx_avail', sa.INTEGER(), nullable=True),
    sa.Column('idx_perf', sa.INTEGER(), nullable=True),
    sa.Column('idx_quality', sa.INTEGER(), nullable=True),
    sa.Column('idx_oee', sa.INTEGER(), nullable=True),
    sa.Column('machine_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('machine_stop',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('turn_num', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('dateStart', sqlite.DATE(), nullable=True),
    sa.Column('timeStart', sqlite.TIME(), nullable=True),
    sa.Column('dateEnd', sqlite.DATE(), nullable=True),
    sa.Column('timeEnd', sqlite.TIME(), nullable=True),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('report_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('machine_stop')
    op.drop_table('report')
    op.drop_table('machine')
    # ### end Alembic commands ###
