"""empty message

Revision ID: db495ff2b300
Revises: d02ec002f703
Create Date: 2017-03-23 13:24:31.605045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db495ff2b300'
down_revision = 'd02ec002f703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machine', sa.Column('serial', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machine', 'serial')
    # ### end Alembic commands ###
